[net]
port = 1212
tickrate = 20

[server]
id = "SpaceDreamMapping"
rules_file = "OrionRuleset"

[auth]
mode = 1

[game]
hostname = "Space Dream // Mapping"
lobbyenabled = false
soft_max_players = 8
role_timers = false
map = "Empty"
map_rotation = false
defaultpreset = "Sandbox"
ipintel_enabled = false

[hub]
advertise = 1
hub_urls = "https://hub.spacestation14.com/"
tags = "region:eu_e,no_tag_infer"
server_url = "ss14s://ss14.pw:1212"

[events]
enabled = false

[queue]
enabled = false

[vote]
enabled = false

[lavaland]
enabled = false

[worldgen]
enabled = false

[shuttle]
emergency = false
arrivals = false
grid_fill = false

[physics]
grid_splitting = false

[mapping]
autosave = true
autosave_interval = 300
autosave_dir = "Autosaves/SpaceDream"

[ooc]
enable_during_round = true

[movement]
mob_pushing = true
