[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 30
port = 3301
bindto = "::,0.0.0.0"
max_connections = 256

[game]
hostname = "[18+][RU] Space Dream"
desc = """18+ сервер на сборке Orion."""

soft_max_players = 80
lobbyduration = 300

[whitelist]
enabled = true

[console]
loginlocal = true

[hub]
advertise = true
tags = "ru;rp:hrp,eu:e"
hub_urls = "https://hub.spacestation14.com/"

[database]
# Database type to use. Can be "sqlite" or "postgres" currently.
engine = "sqlite"