[net]
port = 3301

[server]
id = "SpaceDream"
rules_file = "OrionRuleset"

[auth]
mode = 1
allowlocal = false

[game]
hostname = "[RU][18+][HRP] Space Dream"
desc = "Русскоязычный HRP-сервер 18+."
defaultpreset = "secret"
fallbackpreset = "Extended"
map_pool = "DefaultMapPool"
soft_max_players = 60
lobbyduration = 300

[hub]
advertise = 1
hub_urls = "https://hub.spacestation14.com/"
tags = "18+,lang:ru,rp:high,region:eu_e,no_tag_infer"
server_url = "ss14s://ss14.pw:3301"

[infolinks]
discord = "https://discord.gg/spacedream"
github = "https://github.com/insvrg3ncy/space-station-14"